/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 03:50:51 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class main_ESTest extends main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      main main0 = new main();
      int[] intArray0 = new int[7];
      intArray0[1] = 5629;
      main0.sort(intArray0);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 5629, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      main main0 = new main();
      // Undeclared exception!
      try { 
        main0.sort((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("main", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[21];
      main.main(stringArray0);
  }
}
